### PR TITLE
styles & HTML for whole portal

### PR DESCRIPTION
**Pull request by kevprice83**

### CODE REVIEW

**Comment by kevprice83** [comment]
@lucamaf @manfredbo any feedback can be left here before I merge the PR

**Comment by ManfredBo** [comment]
top left link should refer to to https://open-bank.3scale.net

(currently it refers to https://open-bank.3scale.net/login)

**Comment by ManfredBo** [comment]
On https://open-bank.3scale.net/ section "API Access levels" can you force the 4 blocks to always appear in a 2x2 matrix?

**Comment by ManfredBo** [comment]
Something is not quite right with the line breaks between the headlines and paragraphs here: https://open-bank.3scale.net/about

**Comment by ManfredBo** [comment]
On https://open-bank.3scale.net/:

1. Replace quote “Banking services are necessary. Banks are not” -- Bill Gates, mid 90s -- with headline: "Build out your Open Banking Platform Business Model of the Future with APIs"
2. Generally increase font by 2pt.
3. reduce paragraph width in the text section of the green block.
4. add Gates quote after the text and reduce font: 
“Banking services are necessary. Banks are not” -- Bill Gates, mid 90s

**Comment by ManfredBo** [comment]
Change footer from "GPL Open Banking 2018" to "Red Hat Open Banking Platform 2018"

**Comment by kevprice83** [comment]
> top left link should refer to to https://open-bank.3scale.net
> 
> (currently it refers to https://open-bank.3scale.net/login)

@manfredbo yeah it's pointing to _/admin/applications_ so I'll change it now

**Comment by kevprice83** [comment]
> On https://open-bank.3scale.net/ section "API Access levels" can you force the 4 blocks to always appear in a 2x2 matrix?

Done!

**Comment by ManfredBo** [comment]
> > On https://open-bank.3scale.net/ section "API Access levels" can you force the 4 blocks to always appear in a 2x2 matrix?
> 
> Done!

ok, can you force each block to a smaller, fixed width ?

**Comment by kevprice83** [comment]
> > > On https://open-bank.3scale.net/ section "API Access levels" can you force the 4 blocks to always appear in a 2x2 matrix?
> > 
> > 
> > Done!
> 
> ok, can you force each block to a smaller, fixed width ?

mmm not sure that's possible because this uses the bootstrap grip CSS. Also we need to consider that this content is dynamic so whenever new plans are created then the layout will change. I can see if it's possible to reduce the size of them whilst keeping a 2x2 matrix (might not be possible).

**Comment by ManfredBo** [comment]
> > > > On https://open-bank.3scale.net/ section "API Access levels" can you force the 4 blocks to always appear in a 2x2 matrix?
> > > 
> > > 
> > > Done!
> > 
> > 
> > ok, can you force each block to a smaller, fixed width ?
> 
> mmm not sure that's possible because this uses the bootstrap grip CSS. Also we need to consider that this content is dynamic so whenever new plans are created then the layout will change. I can see if it's possible to reduce the size of them whilst keeping a 2x2 matrix (might not be possible).

I see. then leave it for now. I have more feedback for that and probably better to tackle all that in one go.

**Comment by kevprice83** [comment]
@manfredbo I've made all other changes suggested.

**Comment by ManfredBo** [comment]
top left link  should read "Red Hat Open Banking Platform"

**Comment by kevprice83** [comment]
@ManfredBo I've changed the top left now by changing the root account name. Do you want me to remove _API_ from that link?

**Comment by lucamaf** [comment]
the center service on https://open-bank.3scale.net/ should be called Payment Initiation and not Transaction Initiation.
We should present only Application Plans from Open APIs service and Account and Transaction service.
I would remove the activity log link from the Profile icon when logged in, since we have already the Mail icon for that.
The Bell icon should point to something relevant in terms of notification, can we make it point to rate limit breaches?

**Comment by kevprice83** [comment]
@lucamaf names of services should be changed in the admin portal and then that change can be reflected in the developer portal. A lot of stuff in the homepage right now is just hardcoded. In fact everything there right now can be considered placeholder content, it was never intended to be a final draft.

Yeah we can definitely add more relevant links in the dropdowns, we just need to agree on what should be accessible from there and it's an easy change.

The bell icon for sure can be mapped to the alerts page, we would need to enable alerts on the services to begin with.

**Pull request merged**
